import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-center items-center text-3xl h-32 mx-5">
        Hello :D
      </header>
      <main className='flex justify-center'>
        content
      </main>
    </div>
  )
}
